USE Bibliotheque;

DROP TABLE IF EXISTS Emprunts;
DROP TABLE IF EXISTS Reservations;
DROP TABLE IF EXISTS Livres;
DROP TABLE IF EXISTS Categories;
DROP TABLE IF EXISTS Auteurs;
DROP TABLE IF EXISTS Lecteurs;